import type { Generation } from "./types";

function record(v: unknown): Record<string, unknown> {
  return (v ?? {}) as Record<string, unknown>;
}

export function buildScriptText(generation: Generation): string {
  const script = record(generation.result.steps["script_writer"]?.output) as {
    hook?: string;
    sections?: { title: string; script: string }[];
    cta?: string;
  };
  const lines: string[] = [];
  if (script.hook) lines.push(`HOOK:\n${script.hook}\n`);
  for (const section of script.sections ?? []) {
    lines.push(`${section.title.toUpperCase()}:\n${section.script}\n`);
  }
  if (script.cta) lines.push(`CTA:\n${script.cta}`);
  return lines.join("\n");
}

export function buildMarkdown(generation: Generation, topic: string): string {
  const { steps, final_package: pkg } = generation.result;
  const trend = record(steps["trend_analyst"]?.output) as {
    trending_angles?: string[];
    keywords?: string[];
    content_gap?: string;
  };
  const research = record(steps["research_agent"]?.output) as {
    outline?: { section: string; notes: string }[];
    key_facts?: string[];
    suggested_sources?: string[];
  };
  const thumb = record(steps["thumbnail_strategist"]?.output) as {
    concepts?: { style: string; prompt: string }[];
    color_psychology?: string;
    clickability_score?: number;
  };
  const publish = record(steps["publishing_planner"]?.output) as {
    checklist?: string[];
    best_time?: string;
    weekly_schedule?: string[];
  };

  const md = `# ${pkg.recommended_title || topic}

*Generated by CreatorOS AI — ${new Date(generation.created_at).toLocaleString()} (v${generation.version})*

## Trend Report
${(trend.trending_angles ?? []).map((a) => `- ${a}`).join("\n")}

**Keywords:** ${(trend.keywords ?? []).join(", ")}
**Content gap:** ${trend.content_gap ?? ""}

## Research
${(research.outline ?? []).map((o) => `- **${o.section}** — ${o.notes}`).join("\n")}

**Key facts:**
${(research.key_facts ?? []).map((f) => `- ${f}`).join("\n")}

**Suggested research sources** *(unverified — check before citing)*
${(research.suggested_sources ?? []).map((s) => `- ${s}`).join("\n")}

## Script
${buildScriptText(generation)}

## Thumbnail Strategy
${(thumb.concepts ?? []).map((c) => `- **${c.style}:** ${c.prompt}`).join("\n")}

Color psychology: ${thumb.color_psychology ?? ""}
Estimated clickability: ${thumb.clickability_score ?? "n/a"}/100

## SEO
**Title:** ${pkg.recommended_title}
**Description:** ${pkg.description}
**Tags:** ${pkg.tags.join(", ")}
**Hashtags:** ${pkg.hashtags.join(" ")}

**Chapters:**
${pkg.chapters.map((c) => `- ${c.time} — ${c.label}`).join("\n")}

## Publishing Plan
${(publish.checklist ?? []).map((c) => `- [ ] ${c}`).join("\n")}

Best time to publish: ${publish.best_time ?? pkg.best_publish_time}

**Weekly schedule:**
${(publish.weekly_schedule ?? []).map((w) => `- ${w}`).join("\n")}
`;
  return md;
}

export function downloadTextFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}
